name: Publish Package to npmjs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 0.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - uses: actions/setup-node@v3
        with:
          next-version: ${{ steps.semvers.outputs }}
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@neutron-org'
      #- run: yarn
      #- run: yarn publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
