name: Publish Package to npmjs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Npmjs
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NEUTRON_ACCESS_TOKEN }}
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.NEUTRON_EMAIL }}"
          git config --global user.name "${{ secrets.NEUTRON_USER }}"
      - name: Apply version bump (patch)
        run: yarn version --patch
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Git push version bump
        run: git push origin ${{ steps.branch-name.outputs.current_branch }} --follow-tags --force
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@neutron-org'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
